version: '3.8'
services:
  rpg-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true

