version: '3.8'
services:
  rpg-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./personagens.json:/app/personagens.json
      - ./salas.json:/app/salas.json
    stdin_open: true
    tty: true

